# Generated by Django 4.2.7 on 2024-01-08 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_flashcard_flashcardsblock_delete_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
