# Generated by Django 4.2.7 on 2024-01-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_flashcard_date_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcard',
            options={'ordering': ['date_created']},
        ),
        migrations.AddField(
            model_name='flashcard',
            name='answer_image',
            field=models.ImageField(blank=True, null=True, upload_to='flashcard_images/'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to='flashcard_images/'),
        ),
    ]
