# Generated by Django 4.2.7 on 2024-01-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_alter_flashcard_options_flashcard_answer_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='answer_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='question_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
