# Generated by Django 4.2.7 on 2024-01-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_alter_flashcard_answer_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='answer_text',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='question_text',
            field=models.CharField(max_length=300),
        ),
    ]
